# Generated by Django 3.2 on 2023-05-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, max_length=50, null=True)),
                ('max_volunteer_needed', models.IntegerField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('event_slug', models.SlugField(max_length=150, null=True)),
                ('feature_img', models.ImageField(upload_to='event_feature_img')),
                ('time', models.CharField(max_length=35)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date_posted')),
                ('date_updated', models.DateTimeField(blank=True, null=True, verbose_name='date_updated')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'db_table': 'mainsite_events',
            },
        ),
        migrations.CreateModel(
            name='EventSponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('instr_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
        ),
    ]
