# Generated by Django 3.2 on 2023-05-11 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='related_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventsponsors',
            name='event',
            field=models.ManyToManyField(blank=True, to='events.Events'),
        ),
        migrations.AddField(
            model_name='eventsponsors',
            name='sponsor',
            field=models.ManyToManyField(blank=True, to='events.Sponsors'),
        ),
        migrations.AddField(
            model_name='events',
            name='event_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
