# Generated by Django 5.2.16 on 2026-08-25 02:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import events.models
import events.storage


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventgallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=255)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('secure_url', models.URLField(max_length=1000)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.events')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_event_gallery_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Gallery images',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='GalleryUploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryUploadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staged_file', models.FileField(storage=events.storage.gallery_staging_storage, upload_to=events.models.gallery_staging_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.galleryuploadbatch')),
            ],
        ),
    ]
