# Generated by Django 5.2.16 on 2026-08-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventgalleryimage_galleryuploadbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='gallery_is_public',
            field=models.BooleanField(default=False, help_text='Show database-approved gallery images on the public website.'),
        ),
    ]
