version: '3.8'
services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - '5444:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge