services:
  - type: web
    name: feedsomeone
    runtime: docker
    repo: https://github.com/Combonet-Technology/feedsomeone.git
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    preDeployCommand: python manage.py migrate
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: SETTINGS
        value: config.settings.prod
      - key: DEBUG
        value: "false"
      - key: SITE_ID
        value: "4"
      - key: ALLOWED_HOSTS
        value: oef-service.onrender.com oluwafemiebenezerfoundation.org www.oluwafemiebenezerfoundation.org
      - key: ALLOWED_CSRF
        value: https://oef-service.onrender.com https://oluwafemiebenezerfoundation.org https://www.oluwafemiebenezerfoundation.org
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RECAPTCHA_PUBLIC_KEY_v3
        sync: false
      - key: RECAPTCHA_PRIVATE_KEY_v3
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_NO_REPLY
        sync: false
