# Generated by Django 3.2 on 2023-05-11 12:29

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = []
