# Generated by Django 3.2 on 2023-06-09 16:08
import taggit.managers
from django.db import migrations


def add_tags_field(apps, schema_editor):
    article_model = apps.get_model('blog', 'Article')
    if not hasattr(article_model, 'tags'):
        field = taggit.managers.TaggableManager(
            help_text='A comma-separated list of tags.',
            through='taggit.TaggedItem',
            to='taggit.Tag',
            verbose_name='Tags',
        )
        field.contribute_to_class(article_model, 'tags')


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_article_is_deleted'),
    ]

    operations = [
        migrations.RunPython(add_tags_field),
    ]
