# Generated by Django 3.2 on 2026-08-06 16:52

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('taggit', '0004_auto_20260806_1752'),
        ('blog', '0008_alter_comments_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
