# Generated by Django 5.2.16 on 2026-08-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_editorial_workflow'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[],
        ),
    ]
