# Generated by Django 5.2.16 on 2026-08-22 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_article_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='feature_media',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='featured_articles',
                to='blog.mediaasset',
            ),
        ),
        migrations.AlterField(
            model_name='article',
            name='feature_img',
            field=models.ImageField(
                blank=True,
                default='feature_default.jpg',
                help_text='Legacy local feature image. New editorial images use managed OEF media.',
                upload_to='article_feature_img',
            ),
        ),
    ]
