# Generated by Django 5.2.16 on 2026-09-25 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_mediaasset_source_event_image'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='draft_contributors',
            field=models.ManyToManyField(blank=True, related_name='articles_contributed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='authored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_revisions_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='article_revisions', to='blog.categories'),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='article_revisions_contributed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='direct_bypass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='feature_crop',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='legacy_metadata_unverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='snapshot_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_revisions_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='article_revisions', to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='draft', max_length=24),
        ),
        migrations.AlterField(
            model_name='articlerevision',
            name='status',
            field=models.CharField(choices=[('in_review', 'In review'), ('approved', 'Approved'), ('published', 'Published'), ('changes_requested', 'Changes requested'), ('superseded', 'Superseded')], default='in_review', max_length=24),
        ),
        migrations.CreateModel(
            name='ArticlePublicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_publication_actions', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_events', to='blog.article')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_events', to='blog.articlerevision')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
