# Generated by Django 5.2.16 on 2026-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_editorial_preset_split_and_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
