# Generated by Django 5.2.16 on 2026-09-26 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_article_publication_updated_at'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='articlerevision',
            name='unique_article_revision_number',
        ),
        migrations.RenameField(
            model_name='articlerevision',
            old_name='number',
            new_name='iteration',
        ),
        migrations.AddConstraint(
            model_name='articlerevision',
            constraint=models.UniqueConstraint(fields=('article', 'iteration'), name='unique_article_revision_number'),
        ),
    ]
