# Generated by Django 5.2.16 on 2026-09-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_articlerevision_unique_article_revision_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'permissions': (('submit_article', 'Can submit articles for editorial review'), ('review_article', 'Can review article revisions'), ('publish_article', 'Can publish approved article revisions'), ('publish_without_review', 'Can publish articles without review'))},
        ),
    ]
