# Generated by Django 3.1.2 on 2020-10-26 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('feature_img', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('content', models.TextField()),
                ('budget', models.FloatField(default=20000000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('events_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.events')),
            ],
        ),
    ]
