# Generated by Django 3.1.2 on 2020-10-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_title',
            field=models.CharField(default='Event excerpts', max_length=100),
            preserve_default=False,
        ),
    ]
