# Generated by Django 3.2 on 2023-09-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20230918_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsubscription',
            name='plan_duration',
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='tx_ref',
            field=models.CharField(max_length=255),
        ),
    ]
