# Generated by Django 3.1.2 on 2020-10-27 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainsite', '0003_auto_20201026_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_image', to='mainsite.events'),
        ),
    ]
