# Generated by Django 3.1.2 on 2020-10-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20201027_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='feature_img',
            field=models.ImageField(default='default.jpg', upload_to='events_feature_img'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(default='default.png', upload_to='event_gallery'),
        ),
    ]
