# Generated by Django 3.1.2 on 2020-10-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20201030_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default='Akure, Nigeria', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.CharField(default='9:30am-12:00pm', max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='feature_img',
            field=models.ImageField(default='default.jpg', upload_to='event_feature_img'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='event_pics'),
        ),
    ]
