# Generated by Django 3.1.2 on 2020-11-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20201030_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('tx_ref', models.CharField(max_length=100)),
                ('tr_id', models.IntegerField()),
            ],
        ),
    ]
