# Generated by Django 3.1.2 on 2020-11-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_transactionhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='events',
            name='feature_img',
            field=models.ImageField(upload_to='event_feature_img'),
        ),
    ]
