# Generated by Django 3.1.3 on 2020-12-09 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20201104_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
