# Generated by Django 5.2.16 on 2026-07-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_seed_initial_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='about_oef',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='catalogue_version',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='engagement_type',
            field=models.CharField(choices=[('volunteer', 'Volunteer core team'), ('internship', 'Internship'), ('contract', 'Contract'), ('staff', 'Staff')], default='volunteer', max_length=20),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.CharField(default='Nigeria', max_length=160),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='team',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='time_commitment',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='remote', max_length=20),
        ),
    ]
