# Generated by Django 5.2.16 on 2026-07-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_vacancy_about_oef_vacancy_catalogue_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
