# Generated by Django 5.2.16 on 2026-07-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_vacancy_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyapplication',
            name='acknowledgement_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='notification_error',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='slack_notified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
