# Generated by Django 5.2.16 on 2026-07-18 04:15

from django.db import migrations, models

import opportunities.models
import opportunities.storage


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_vacancyapplication_acknowledgement_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapplication',
            name='cv',
            field=models.FileField(storage=opportunities.storage.VacancyCVStorage(), upload_to=opportunities.models.vacancy_cv_upload_to),
        ),
    ]
