# Generated by Django 5.2.16 on 2026-07-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_alter_vacancyapplication_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyapplication',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='newsletter_subscribed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
