# Generated by Django 5.2.16 on 2026-07-23 10:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import opportunities.models
import opportunities.storage


def set_offer_rls(schema_editor, enabled):
    if schema_editor.connection.vendor != 'postgresql':
        return

    action = 'ENABLE' if enabled else 'DISABLE'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'ALTER TABLE public.opportunities_volunteeroffer {action} ROW LEVEL SECURITY;'
        )


def enable_offer_rls(apps, schema_editor):
    set_offer_rls(schema_editor, enabled=True)


def disable_offer_rls(apps, schema_editor):
    set_offer_rls(schema_editor, enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0009_enable_rls_for_opportunities_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancyapplication',
            options={'ordering': ('-created_at',), 'permissions': (('send_volunteer_offer', 'Can prepare and send volunteer offers'),)},
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('offered', 'Offered'), ('offer_accepted', 'Offer accepted'), ('agreement_signed', 'Agreement signed'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('not_selected', 'Not selected'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed')], default='received', max_length=20),
        ),
        migrations.CreateModel(
            name='VolunteerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('role_title', models.CharField(max_length=255)),
                ('letter_date', models.DateField()),
                ('start_date', models.DateField()),
                ('initial_period', models.CharField(max_length=120)),
                ('weekly_commitment', models.CharField(max_length=160)),
                ('work_arrangement', models.TextField()),
                ('reporting_contact', models.CharField(max_length=255)),
                ('role_contribution', models.TextField()),
                ('acceptance_deadline', models.DateField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('delivery_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('letter_pdf', models.FileField(blank=True, storage=opportunities.storage.VacancyPrivateDocumentStorage(), upload_to=opportunities.models.volunteer_offer_upload_to)),
                ('brevo_message_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('delivery_error', models.TextField(blank=True, editable=False)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_offer', to='opportunities.vacancyapplication')),
                ('sent_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_offers_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(
            enable_offer_rls,
            reverse_code=disable_offer_rls,
        ),
    ]
