# Generated by Django 3.2 on 2026-08-06 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0013_vacancyapplication_rejection_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancyapplication',
            options={'ordering': ('-created_at',), 'permissions': (('send_volunteer_offer', 'Can prepare and send volunteer offers'), ('send_onboarding_email', 'Can send volunteer onboarding emails'), ('send_rejection_email', 'Can send volunteer rejection emails'), ('send_interview_invitation', 'Can send volunteer interview invitations'))},
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='interview_email_batch_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='interview_email_error',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='interview_email_message_id',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='interview_email_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='interview_email_sent_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='interview_email_status',
            field=models.CharField(choices=[('not_sent', 'Not sent'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_sent', editable=False, max_length=20),
        ),
    ]
