# Generated by Django 3.2 on 2026-08-07 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0014_vacancy_application_acceptance_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyapplication',
            name='shortlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='shortlisted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_shortlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
