# Generated by Django 5.2.16 on 2026-09-24 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0017_enable_rls_for_private_document_deletions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('intake_closed', 'Intake closed'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('intake_closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('offered', 'Offered'), ('offer_accepted', 'Offer accepted'), ('agreement_signed', 'Agreement signed'), ('appointed', 'Appointed'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('not_selected', 'Not selected'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed')], default='received', max_length=20),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='opportunities.recruitmentcohort'),
        ),
    ]
