# Generated by Django 5.2.16 on 2026-09-24 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0018_recruitmentcohort_alter_vacancyapplication_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyapplication',
            name='agreement_verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='agreement_verified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements_verified_for_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='appointed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='appointed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_appointed', to=settings.AUTH_USER_MODEL),
        ),
    ]
