# Generated by Django 5.2.16 on 2026-09-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0019_vacancyapplication_agreement_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='legacy_unassigned',
            field=models.BooleanField(default=True, editable=False, help_text='Historical opening created before cohort assignment was required.'),
            preserve_default=False,
        ),
    ]
