# Generated by Django 5.2.16 on 2026-09-26 05:10

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def preserve_application_cohorts(apps, schema_editor):
    alias = schema_editor.connection.alias
    applications = apps.get_model('opportunities', 'VacancyApplication').objects.using(alias)
    vacancies = apps.get_model('opportunities', 'Vacancy').objects.using(alias)
    applications.update(cohort_id=models.Subquery(
        vacancies.filter(pk=models.OuterRef('vacancy_id')).values('cohort_id')[:1],
    ))
    duplicates = applications.annotate(
        email_key=django.db.models.functions.text.Lower('email'),
    ).values('vacancy_id', 'cohort_id', 'email_key').annotate(
        total=models.Count('pk'),
    ).filter(total__gt=1)
    if duplicates.exists():
        raise RuntimeError('Reconcile case-insensitive duplicate applications before cohort migration.')


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0023_plain_appointed_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vacancyapplication',
            name='unique_vacancy_applicant',
        ),
        migrations.RemoveConstraint(
            model_name='vacancyapplication',
            name='unique_vacancy_email',
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='opportunities.recruitmentcohort'),
        ),
        migrations.RunPython(preserve_application_cohorts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='recruitmentcohort',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('intake_closed', 'Closed'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Current intake cohort. Leave blank for unbatched recruitment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='opportunities.recruitmentcohort'),
        ),
        migrations.AddConstraint(
            model_name='vacancyapplication',
            constraint=models.UniqueConstraint(fields=('vacancy', 'cohort', 'applicant'), name='unique_cohort_vacancy_applicant'),
        ),
        migrations.AddConstraint(
            model_name='vacancyapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('cohort__isnull', True)), fields=('vacancy', 'applicant'), name='unique_unbatched_vacancy_applicant'),
        ),
        migrations.AddConstraint(
            model_name='vacancyapplication',
            constraint=models.UniqueConstraint(models.F('vacancy'), models.F('cohort'), django.db.models.functions.text.Lower('email'), condition=models.Q(('cohort__isnull', False)), name='unique_cohort_vacancy_email'),
        ),
        migrations.AddConstraint(
            model_name='vacancyapplication',
            constraint=models.UniqueConstraint(models.F('vacancy'), django.db.models.functions.text.Lower('email'), condition=models.Q(('cohort__isnull', True)), name='unique_unbatched_vacancy_email'),
        ),
    ]
