"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from ext_libs.ckeditor.config import base

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Application definition
SECRET_KEY = os.environ.get('SECRET_KEY')
INSTALLED_APPS = [
    'user.apps.UserConfig',
    'baton',
    # 'djangocms_admin_style',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'taggit',
    'django.contrib.sitemaps',
    'mainsite.apps.MainsiteConfig',
    'blog.apps.BlogConfig',
    'events.apps.EventsConfig',
    'contact.apps.ContactConfig',
    'opportunities.apps.OpportunitiesConfig',
    'django.contrib.postgres',
    'crispy_forms',
    'imagefit',
    'import_export',
    'django.contrib.humanize',
    'errors.apps.ErrorsConfig',
    'captcha',
    'baton.autodiscover',
    # 'cms',
    'admin_honeypot',
    'honeypot',
    'social_django',
    'django_extensions',
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    # 'cms.middleware.utils.ApphookReloadMiddleware'
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'cms.middleware.user.CurrentUserMiddleware',
    # 'cms.middleware.page.CurrentPageMiddleware',
    # 'cms.middleware.toolbar.ToolbarMiddleware',
    # 'cms.middleware.language.LanguageCookieMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'cms.context_processors.cms_settings',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en-us', 'English'),
    ('de', 'German'),
    ('fr', 'French'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = 'profile'
LOGIN_URL = 'login'

IMAGEFIT_ROOT = BASE_DIR

AUTH_USER_MODEL = 'user.UserProfile'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SITE_ID = int(os.environ.get('SITE_ID', '1'))
RECAPTCHA_PUBLIC_KEY = str(os.environ.get('RECAPTCHA_PUBLIC_KEY_v3'))
RECAPTCHA_PRIVATE_KEY = str(os.environ.get('RECAPTCHA_PRIVATE_KEY_v3'))
RECAPTCHA_MIN_SCORE = float(os.environ.get('RECAPTCHA_MIN_SCORE', '0.5'))
RECAPTCHA_TIMEOUT_SECONDS = float(os.environ.get('RECAPTCHA_TIMEOUT_SECONDS', '5'))
REGISTRATION_RATE_LIMIT = int(os.environ.get('REGISTRATION_RATE_LIMIT', '5'))
REGISTRATION_RATE_LIMIT_WINDOW = int(os.environ.get('REGISTRATION_RATE_LIMIT_WINDOW', '3600'))

# Historical public galleries are fetched server-side from an allow-list of
# verified Cloudinary tags. Keep disabled until image consent/privacy review is
# complete, then set CLOUDINARY_GALLERY_ENABLED=true in the deployment.
CLOUDINARY_GALLERY_ENABLED = os.environ.get('CLOUDINARY_GALLERY_ENABLED', '').lower() == 'true'
CLOUDINARY_GALLERY_CACHE_SECONDS = int(os.environ.get('CLOUDINARY_GALLERY_CACHE_SECONDS', '900'))
CLOUDINARY_GALLERY_PUBLICATION_TAG = os.environ.get(
    'CLOUDINARY_GALLERY_PUBLICATION_TAG',
    'publication-approved',
)
CLOUDINARY_GALLERIES = {
    'feed-someone-1.0': {
        'tag': 'feed-someone-1.0',
        'title': 'Feed Someone 1.0',
        'date': '27 December 2019',
        'location': 'Akure, Ondo State',
        'summary': 'Meals and drinks shared with an underserved street-connected community.',
        'library_count': 25,
    },
    'feed-someone-2.0': {
        'tag': 'feed-someone-2.0',
        'title': 'Feed Someone 2.0',
        'date': 'December 2020',
        'location': 'Akure, Ondo State',
        'summary': 'Relief support delivered to two children\'s homes and an underserved community.',
        'library_count': 74,
    },
}

BATON = {
    'SITE_HEADER': 'Oluwafemi Ebenezer Foundation',
    'SITE_TITLE': 'OEF BACKEND',
    'INDEX_TITLE': 'OEF administration',
    'SUPPORT_HREF': 'mailto:info@oluwafemiebenezerfoundation.org',
    'COPYRIGHT': 'copyright © 2020 <a href="https://www.otto.to.it">Otto srl</a>',  # noqa
    'POWERED_BY': '<a href="https://www.otto.to.it">Otto srl</a>',
    'CONFIRM_UNSAVED_CHANGES': True,
    'SHOW_MULTIPART_UPLOADING': True,
    'ENABLE_IMAGES_PREVIEW': True,
    'CHANGELIST_FILTERS_IN_MODAL': True,
    'CHANGELIST_FILTERS_ALWAYS_OPEN': False,
    'CHANGELIST_FILTERS_FORM': True,
    'MENU_ALWAYS_COLLAPSED': False,
    'MENU_TITLE': 'Menu',
    'MESSAGES_TOASTS': False,
    'GRAVATAR_DEFAULT_IMG': 'retro',
    'LOGIN_SPLASH': '/static/core/img/login-splash.png',
    'SEARCH_FIELD': {
        'label': 'Search contents...',
        'url': '/search/',
    },
    'MENU': (
        {'type': 'title', 'label': 'main', 'apps': ('auth',)},
        {
            'type': 'app',
            'name': 'auth',
            'label': 'Authentication',
            'icon': 'fa fa-lock',
            'models': (
                {
                    'name': 'user',
                    'label': 'Users'
                },
                {
                    'name': 'group',
                    'label': 'Groups'
                },
            )
        },
        {'type': 'title', 'label': 'Contents', 'apps': ('flatpages',)},
        {'type': 'model', 'label': 'Pages', 'name': 'flatpage', 'app': 'flatpages'},
        {
            'type': 'free', 'label': 'Custom Link', 'url': 'http://www.google.it',
            'perms': ('flatpages.add_flatpage', 'auth.change_user')
        },
        {
            'type': 'free', 'label': 'My parent voice', 'default_open': True, 'children':
            [
                {'type': 'model', 'label': 'A Model', 'name': 'mymodelname', 'app': 'myapp'},
                {'type': 'free', 'label': 'Another custom link', 'url': 'http://www.google.it'},
            ]
        },
    ),
    # 'ANALYTICS': {
    #     'CREDENTIALS': os.path.join(BASE_DIR, 'credentials.json'),
    #     'VIEW_ID': '12345678',
    # }
}

CMS_TEMPLATES = [
    ('index.html', 'Home page template'),
]

AUTHENTICATION_BACKENDS = [
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.linkedin.LinkedinOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]
IMAGEFIT_PRESETS = {
    'thumbnail': {'width': 64, 'height': 64, 'crop': True},
    'my_preset1': {'width': 300, 'height': 220},
    'my_preset2': {'width': 100},
}

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_NO_REPLY = os.environ.get('EMAIL_NO_REPLY')
GMAIL_EMAIL = os.environ.get('GMAIL_EMAIL')
OUTLOOK_EMAIL = os.environ.get('OUTLOOK_EMAIL')

HONEYPOT_FIELD_NAME = os.environ.get('HONEYPOT_FIELD_NAME', 'phonenumber')
HONEYPOT_VALUE = os.environ.get('HONEYPOT_VALUE', '+234812345678')

SOCIAL_AUTH_FACEBOOK_KEY = os.environ.get('FACEBOOK_KEY')
SOCIAL_AUTH_FACEBOOK_SECRET = os.environ.get('FACEBOOK_SECRET')
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'locale': 'ru_RU',
    'fields': 'id, name, email, age_range'
}

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "ext_libs.python_social.social_auth_pipeline.merge_user",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
    "ext_libs.python_social.social_auth_pipeline.create_volunteer"
)

SOCIAL_AUTH_TWITTER_KEY = os.environ.get('TWITTER_API_KEY')
SOCIAL_AUTH_TWITTER_SECRET = os.environ.get('TWITTER_API_SECRET')
SOCIAL_AUTH_TWITTER_OAUTH2_SECRET = os.environ.get('TWITTER_OAUTH2_CLIENT_ID_KEY')
SOCIAL_AUTH_TWITTER_OAUTH2_KEY = os.environ.get('TWITTER_OAUTH2_CLIENT_SECRET')

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('GOOGLE_OAUTH2_SECRET')
SOCIAL_AUTH_GOOGLE_PLUS_KEY = os.environ.get('GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_PLUS_SECRET = os.environ.get('GOOGLE_OAUTH2_SECRET')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile'
]

SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = os.environ.get('LINKEDIN_OAUTH2_KEY')
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = os.environ.get('LINKEDIN_OAUTH2_SECRET')
SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE = ['r_liteprofile', 'r_emailaddress']
SOCIAL_AUTH_LINKEDIN_OAUTH2_EXTRA_DATA = [('id', 'id'),
                                          ('firstName', 'first_name'),
                                          ('lastName', 'last_name'),
                                          ('emailAddress', 'email_address')]
SOCIAL_AUTH_LINKEDIN_OAUTH2_FIELD_SELECTORS = ['emailAddress']

SOCIAL_AUTH_USER_FIELDS = ['email']

BREVO_API_KEY = os.environ.get('BREVO_API_KEY')
BREVO_API_BASE_URL = os.environ.get('BREVO_API_BASE_URL', 'https://api.brevo.com/v3')
BREVO_SENDER_EMAIL = os.environ.get('BREVO_SENDER_EMAIL') or EMAIL_NO_REPLY or EMAIL_HOST_USER
BREVO_SENDER_NAME = os.environ.get('BREVO_SENDER_NAME', 'Oluwafemi Ebenezer Foundation')
BREVO_REPLY_TO_EMAIL = os.environ.get('BREVO_REPLY_TO_EMAIL') or GMAIL_EMAIL
BREVO_CONTACT_RECIPIENTS = [
    email.strip()
    for email in os.environ.get('BREVO_CONTACT_RECIPIENTS', GMAIL_EMAIL or '').split(',')
    if email.strip()
]
BREVO_NEWSLETTER_LIST_ID = os.environ.get('BREVO_NEWSLETTER_LIST_ID')
BREVO_NEWSLETTER_LIST_ID = int(BREVO_NEWSLETTER_LIST_ID) if BREVO_NEWSLETTER_LIST_ID else None
BREVO_TIMEOUT_SECONDS = float(os.environ.get('BREVO_TIMEOUT_SECONDS', '10'))

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_FILENAME_GENERATOR = 'utils.file.get_filename'
CKEDITOR_IMAGE_BACKEND = 'ckeditor_uploader.backends.PillowBackend'
CKEDITOR_FORCE_JPEG_COMPRESSION = True
CKEDITOR_IMAGE_QUALITY = 90
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_RESTRICT_BY_DATE = True
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter',
             'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ],
        'height': 300,
        'width': 750,
    },
    'article': base
}

TEST_RUNNER = 'custom_test_runner.TestRunner'
TEST_OUTPUT_DIR = 'test-reports'
SLACK_WEBHOOK_URL = os.environ.get('SLACK_WEBHOOK_URL')
STAGE = 'bcx'
