# Generated by Django 3.1.2 on 2020-10-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201027_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reason_joined',
            field=models.TextField(default='The burden to help the needy has never been more than now'),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.CharField(default='I am a developer (replace with yours)- 100 character limit', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
