# Generated by Django 3.2 on 2023-05-12 19:39
import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import utils.enums


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_auto_20230512_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='userprofile_ptr',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='userprofile_ptr',
        ),
        migrations.AddField(
            model_name='donor',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True,
                                   serialize=False, verbose_name='UUID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[(utils.enums.EthnicityEnum['HAUSA'], 'HAUSA'),
                                                        (utils.enums.EthnicityEnum['IGBO'], 'IGBO'),
                                                        (utils.enums.EthnicityEnum['YORUBA'], 'YORUBA'),
                                                        (utils.enums.EthnicityEnum['FULANI'], 'FULANI'),
                                                        (utils.enums.EthnicityEnum['IBIBIO'], 'IBIBIO'),
                                                        (utils.enums.EthnicityEnum['EDO'], 'EDO'),
                                                        (utils.enums.EthnicityEnum['IJAW'], 'IJAW'),
                                                        (utils.enums.EthnicityEnum['ITSEKIRI'], 'ITSEKIRI'),
                                                        (utils.enums.EthnicityEnum['BENIN'], 'BENIN'),
                                                        (utils.enums.EthnicityEnum['IGALA'], 'IGALA'),
                                                        (utils.enums.EthnicityEnum['IDOMA'], 'IDOMA'),
                                                        (utils.enums.EthnicityEnum['KANURI'], 'KANURI'),
                                                        (utils.enums.EthnicityEnum['EFIK'], 'EFIK'),
                                                        (utils.enums.EthnicityEnum['BWARI'], 'BWARI'),
                                                        (utils.enums.EthnicityEnum['TIV'], 'TIV'),
                                                        (utils.enums.EthnicityEnum['BIROM'], 'BIROM'),
                                                        (utils.enums.EthnicityEnum['ANGERS'], 'ANGERS'),
                                                        (utils.enums.EthnicityEnum['IDOMINA'], 'IDOMINA'),
                                                        (utils.enums.EthnicityEnum['EBIRA'], 'EBIRA')], max_length=30,
                                   null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True,
                                   serialize=False, verbose_name='UUID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='religion',
            field=models.CharField(blank=True, choices=[(utils.enums.ReligionEnum['CHRISTIANITY'], 'CHRISTIANITY'),
                                                        (utils.enums.ReligionEnum['ISLAM'], 'ISLAM'),
                                                        (utils.enums.ReligionEnum['TRADITIONALIST'], 'TRADITIONALIST'),
                                                        (utils.enums.ReligionEnum['OTHERS'], 'OTHERS')], max_length=30,
                                   null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='state_of_residence',
            field=models.CharField(blank=True, choices=[(utils.enums.StateEnum['ABIA'], 'ABIA'),
                                                        (utils.enums.StateEnum['ADAMAWA'], 'ADAMAWA'),
                                                        (utils.enums.StateEnum['AKWAIBOM'], 'AKWAIBOM'),
                                                        (utils.enums.StateEnum['ANAMBRA'], 'ANAMBRA'),
                                                        (utils.enums.StateEnum['BAUCHI'], 'BAUCHI'),
                                                        (utils.enums.StateEnum['BAYELSA'], 'BAYELSA'),
                                                        (utils.enums.StateEnum['BENUE'], 'BENUE'),
                                                        (utils.enums.StateEnum['BORNO'], 'BORNO'),
                                                        (utils.enums.StateEnum['CROSSRIVER'], 'CROSS RIVER'),
                                                        (utils.enums.StateEnum['DELTA'], 'DELTA'),
                                                        (utils.enums.StateEnum['EBONYI'], 'EBONYI'),
                                                        (utils.enums.StateEnum['EDO'], 'EDO'),
                                                        (utils.enums.StateEnum['EKITI'], 'EKITI'),
                                                        (utils.enums.StateEnum['ENUGU'], 'ENUGU'),
                                                        (utils.enums.StateEnum['GOMBE'], 'GOMBE'),
                                                        (utils.enums.StateEnum['IMO'], 'IMO'),
                                                        (utils.enums.StateEnum['JIGAWA'], 'JIGAWA'),
                                                        (utils.enums.StateEnum['KADUNA'], 'KADUNA'),
                                                        (utils.enums.StateEnum['KANO'], 'KANO'),
                                                        (utils.enums.StateEnum['KATSINA'], 'KATSINA'),
                                                        (utils.enums.StateEnum['KEBBI'], 'KEBBI'),
                                                        (utils.enums.StateEnum['KOGI'], 'KOGI'),
                                                        (utils.enums.StateEnum['KWARA'], 'KWARA'),
                                                        (utils.enums.StateEnum['LAGOS'], 'LAGOS'),
                                                        (utils.enums.StateEnum['NASARAWA'], 'NASARAWA'),
                                                        (utils.enums.StateEnum['NIGER'], 'NIGER'),
                                                        (utils.enums.StateEnum['OGUN'], 'OGUN'),
                                                        (utils.enums.StateEnum['ONDO'], 'ONDO'),
                                                        (utils.enums.StateEnum['OSUN'], 'OSUN'),
                                                        (utils.enums.StateEnum['OYO'], 'OYO'),
                                                        (utils.enums.StateEnum['PLATEAU'], 'PLATEAU'),
                                                        (utils.enums.StateEnum['RIVERS'], 'RIVERS'),
                                                        (utils.enums.StateEnum['SOKOTO'], 'SOKOTO'),
                                                        (utils.enums.StateEnum['TARABA'], 'TARABA'),
                                                        (utils.enums.StateEnum['YOBE'], 'YOBE'),
                                                        (utils.enums.StateEnum['ZAMFARA'], 'ZAMFARA'),
                                                        (utils.enums.StateEnum['FCT'], 'FCT-ABUJA')], max_length=30,
                                   null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='volunteer', to=settings.AUTH_USER_MODEL),
        ),
    ]
