# Generated by Django 3.2 on 2023-05-13 07:47

from django.db import migrations, models

import utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230512_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='state_of_residence',
            field=models.CharField(blank=True, choices=[(utils.enums.StateEnum['ABIA'], 'ABIA'), (
            utils.enums.StateEnum['ADAMAWA'], 'ADAMAWA'), (utils.enums.StateEnum['AKWAIBOM'], 'AKWAIBOM'), (
                                                        utils.enums.StateEnum['ANAMBRA'], 'ANAMBRA'), (
                                                        utils.enums.StateEnum['BAUCHI'], 'BAUCHI'), (
                                                        utils.enums.StateEnum['BAYELSA'], 'BAYELSA'), (
                                                        utils.enums.StateEnum['BENUE'], 'BENUE'), (
                                                        utils.enums.StateEnum['BORNO'], 'BORNO'), (
                                                        utils.enums.StateEnum['CROSSRIVER'], 'CROSS RIVER'), (
                                                        utils.enums.StateEnum['DELTA'], 'DELTA'), (
                                                        utils.enums.StateEnum['EBONYI'], 'EBONYI'), (
                                                        utils.enums.StateEnum['EDO'], 'EDO'), (
                                                        utils.enums.StateEnum['EKITI'], 'EKITI'), (
                                                        utils.enums.StateEnum['ENUGU'], 'ENUGU'), (
                                                        utils.enums.StateEnum['GOMBE'], 'GOMBE'), (
                                                        utils.enums.StateEnum['IMO'], 'IMO'), (
                                                        utils.enums.StateEnum['JIGAWA'], 'JIGAWA'), (
                                                        utils.enums.StateEnum['KADUNA'], 'KADUNA'), (
                                                        utils.enums.StateEnum['KANO'], 'KANO'), (
                                                        utils.enums.StateEnum['KATSINA'], 'KATSINA'), (
                                                        utils.enums.StateEnum['KEBBI'], 'KEBBI'), (
                                                        utils.enums.StateEnum['KOGI'], 'KOGI'), (
                                                        utils.enums.StateEnum['KWARA'], 'KWARA'), (
                                                        utils.enums.StateEnum['LAGOS'], 'LAGOS'), (
                                                        utils.enums.StateEnum['NASARAWA'], 'NASARAWA'), (
                                                        utils.enums.StateEnum['NIGER'], 'NIGER'), (
                                                        utils.enums.StateEnum['OGUN'], 'OGUN'), (
                                                        utils.enums.StateEnum['ONDO'], 'ONDO'), (
                                                        utils.enums.StateEnum['OSUN'], 'OSUN'), (
                                                        utils.enums.StateEnum['OYO'], 'OYO'), (
                                                        utils.enums.StateEnum['PLATEAU'], 'PLATEAU'), (
                                                        utils.enums.StateEnum['RIVERS'], 'RIVERS'), (
                                                        utils.enums.StateEnum['SOKOTO'], 'SOKOTO'), (
                                                        utils.enums.StateEnum['TARABA'], 'TARABA'), (
                                                        utils.enums.StateEnum['YOBE'], 'YOBE'), (
                                                        utils.enums.StateEnum['ZAMFARA'], 'ZAMFARA'), (
                                                        utils.enums.StateEnum['FCT'], 'FCT-ABUJA')], max_length=30, null=True, verbose_name='select state'),
        ),
    ]
