# Generated by Django 3.1.2 on 2020-11-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201101_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='innovator',
            field=models.BooleanField(default=False),
        ),
    ]
