# Generated by Django 3.2 on 2023-05-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_volunteer_state_of_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('HAUSA', 'HAUSA'), ('IGBO', 'IGBO'), ('YORUBA', 'YORUBA'), ('FULANI', 'FULANI'), ('IBIBIO', 'IBIBIO'), ('EDO', 'EDO'), ('IJAW', 'IJAW'), ('ITSEKIRI', 'ITSEKIRI'), ('BENIN', 'BENIN'), ('IGALA', 'IGALA'), ('IDOMA', 'IDOMA'), ('KANURI', 'KANURI'), ('EFIK', 'EFIK'), ('BWARI', 'BWARI'), ('TIV', 'TIV'), ('BIROM', 'BIROM'), ('ANGERS', 'ANGERS'), ('IDOMINA', 'IDOMINA'), ('EBIRA', 'EBIRA')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='religion',
            field=models.CharField(blank=True, choices=[('CHRISTIANITY', 'CHRISTIANITY'), ('ISLAM', 'ISLAM'), ('TRADITIONALIST', 'TRADITIONALIST'), ('OTHERS', 'OTHERS')], max_length=30, null=True),
        ),
    ]
