# Generated by Django 3.1.3 on 2020-12-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_innovator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.CharField(default='replace with a short introduction about yourself', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(default='#', max_length=100, null=True),
        ),
    ]
