# Generated by Django 3.2 on 2023-05-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
