# Generated by Django 3.2 on 2023-09-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_tags'),
        ('events', '0002_initial'),
        ('social_django', '0012_merge_0009_auto_20230519_1245_0011_alter_id_fields'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user', '0009_delete_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
