# Generated by Django 5.2.16 on 2026-07-30 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0011_create_recruitment_manager_group'),
        ('user', '0011_alter_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=255)),
                ('engagement_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('internship', 'Intern'), ('contract', 'Contractor'), ('staff', 'Employee'), ('trustee', 'Trustee')], default='volunteer', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('inactive', 'Inactive'), ('offboarded', 'Offboarded')], default='invited', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('access_granted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('access_revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('invitation_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('invitation_message_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('invitation_error', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_granted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_access_grants', to=settings.AUTH_USER_MODEL)),
                ('access_revoked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_access_revocations', to=settings.AUTH_USER_MODEL)),
                ('source_application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member', to='opportunities.vacancyapplication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__first_name', 'user__last_name', 'user__email'),
            },
        ),
    ]
