# Generated by Django 5.2.16 on 2026-09-24 23:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0018_recruitmentcohort_alter_vacancyapplication_status_and_more'),
        ('user', '0012_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('full_name', 'primary_email'), 'permissions': (('manage_team_access', 'Can manage delegable team backend access'), ('manage_team_engagement', 'Can appoint and manage team engagements'))},
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BackendAccessChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('before_groups', models.JSONField(default=list)),
                ('after_groups', models.JSONField(default=list)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backend_access_actions', to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backend_access_changes', to='user.teammember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backend_access_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role_title', models.CharField(max_length=255)),
                ('engagement_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('internship', 'Intern'), ('contract', 'Contractor'), ('staff', 'Employee'), ('trustee', 'Trustee')], default='volunteer', max_length=20)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('ended', 'Ended')], default='onboarding', max_length=20)),
                ('onboarding_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('onboarding_started_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_endings', to=settings.AUTH_USER_MODEL)),
                ('onboarding_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_onboarding_completions', to=settings.AUTH_USER_MODEL)),
                ('onboarding_started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_onboarding_starts', to=settings.AUTH_USER_MODEL)),
                ('source_application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement', to='opportunities.vacancyapplication')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='user.teammember')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
