# Generated by Django 5.2.16 on 2026-09-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_oef_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
