# Generated by Django 5.2.16 on 2026-09-27 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_current_presets(apps, schema_editor):
    member_model = apps.get_model('user', 'TeamMember')
    allowed = {'OEF Writers', 'OEF Reviewers', 'OEF Publishers', 'Recruitment Manager'}
    for member in member_model.objects.using(schema_editor.connection.alias).exclude(user=None).iterator():
        member.desired_backend_groups = sorted(set(member.user.groups.values_list('name', flat=True)) & allowed)
        member.save(using=schema_editor.connection.alias, update_fields=('desired_backend_groups',))


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_one_current_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendaccesschange',
            name='after_enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='backendaccesschange',
            name='before_enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='backendaccessinvitation',
            name='access_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='backendaccessinvitation',
            name='recipient_email',
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name='backendaccessinvitation',
            name='reset_password',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='backendaccessinvitation',
            name='staff_required',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='backendaccessinvitation',
            name='used_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='access_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='desired_backend_groups',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=80)),
                ('residential_address', models.TextField(blank=True, max_length=2000)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, choices=[('ABIA', 'ABIA'), ('ADAMAWA', 'ADAMAWA'), ('AKWAIBOM', 'AKWAIBOM'), ('ANAMBRA', 'ANAMBRA'), ('BAUCHI', 'BAUCHI'), ('BAYELSA', 'BAYELSA'), ('BENUE', 'BENUE'), ('BORNO', 'BORNO'), ('CROSSRIVER', 'CROSS RIVER'), ('DELTA', 'DELTA'), ('EBONYI', 'EBONYI'), ('EDO', 'EDO'), ('EKITI', 'EKITI'), ('ENUGU', 'ENUGU'), ('GOMBE', 'GOMBE'), ('IMO', 'IMO'), ('JIGAWA', 'JIGAWA'), ('KADUNA', 'KADUNA'), ('KANO', 'KANO'), ('KATSINA', 'KATSINA'), ('KEBBI', 'KEBBI'), ('KOGI', 'KOGI'), ('KWARA', 'KWARA'), ('LAGOS', 'LAGOS'), ('NASARAWA', 'NASARAWA'), ('NIGER', 'NIGER'), ('OGUN', 'OGUN'), ('ONDO', 'ONDO'), ('OSUN', 'OSUN'), ('OYO', 'OYO'), ('PLATEAU', 'PLATEAU'), ('RIVERS', 'RIVERS'), ('SOKOTO', 'SOKOTO'), ('TARABA', 'TARABA'), ('YOBE', 'YOBE'), ('ZAMFARA', 'ZAMFARA'), ('FCT', 'FCT-ABUJA')], max_length=30)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, default='NG', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_relationship', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('primary_device', models.CharField(blank=True, max_length=255)),
                ('working_from', models.CharField(blank=True, max_length=255)),
                ('reliable_internet', models.BooleanField(blank=True, null=True)),
                ('technical_challenges', models.BooleanField(blank=True, null=True)),
                ('challenge_details', models.TextField(blank=True, max_length=3000)),
                ('editable', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='user.teammember')),
            ],
            options={
                'permissions': [('manage_private_profiles', 'Can view private member profiles and reopen editing')],
            },
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cv', 'CV / resume'), ('identity', 'Identification document'), ('certificates', 'Educational / professional certificates'), ('photo', 'Passport photograph')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=80)),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='user.memberdetails')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfileRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='user.memberdetails')),
            ],
        ),
        migrations.RunPython(preserve_current_presets, migrations.RunPython.noop),
    ]
