# Generated by Django 5.2.16 on 2026-09-27 18:25

from django.db import migrations
from django.utils import timezone


def retire_profiles(apps, schema_editor):
    alias = schema_editor.connection.alias
    for name in ('MemberDocument', 'MemberProfileRevision'):
        if apps.get_model('user', name).objects.using(alias).exists():
            raise RuntimeError('Export and explicitly clear private profile data before removing this feature.')
    profiles = apps.get_model('user', 'MemberDetails').objects.using(alias).select_related('team_member')
    ignored = {'id', 'team_member', 'full_name', 'country', 'editable', 'updated_at', 'revision'}
    for profile in profiles:
        if (
            profile.full_name != profile.team_member.full_name
            or profile.country != 'NG' or not profile.editable or profile.revision != 0
            or any(getattr(profile, field.name) not in (None, '')
                   for field in profile._meta.fields if field.name not in ignored)
        ):
            raise RuntimeError('Export and explicitly clear private profile data before removing this feature.')
    # A profile-only invitation must never become a staff password-reset link.
    apps.get_model('user', 'BackendAccessInvitation').objects.using(alias).filter(
        staff_required=False, used_at=None,
    ).update(used_at=timezone.now())
    apps.get_model('contenttypes', 'ContentType').objects.using(alias).filter(
        app_label='user', model__in=('memberdetails', 'memberdocument', 'memberprofilerevision'),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_manual_access_and_member_profiles'),
    ]

    operations = [
        migrations.RunPython(retire_profiles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='memberdocument',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='memberprofilerevision',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='memberdocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='memberprofilerevision',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='backendaccessinvitation',
            name='staff_required',
        ),
        migrations.DeleteModel(
            name='MemberDetails',
        ),
        migrations.DeleteModel(
            name='MemberDocument',
        ),
        migrations.DeleteModel(
            name='MemberProfileRevision',
        ),
    ]
